/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    posts: Post;
    redirects: Redirect;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    siteSettings: SiteSetting;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  components?:
    | (
        | {
            heading: string;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image: number | Media;
            ctaLabel?: string | null;
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading: string;
            subheading?: string | null;
            groups: {
              label: string;
              services: {
                title: string;
                description: string;
                icon:
                  | 'bell'
                  | 'certified'
                  | 'checkCircle'
                  | 'deck'
                  | 'documentCheck'
                  | 'glasses'
                  | 'gutter'
                  | 'locationHeart'
                  | 'meditation'
                  | 'messages'
                  | 'money'
                  | 'paintBrush'
                  | 'paymentCard'
                  | 'roof'
                  | 'roofCleaning'
                  | 'roofInsulation'
                  | 'roofRepair'
                  | 'roofReplacement'
                  | 'shieldCheck'
                  | 'shield'
                  | 'siding'
                  | 'smile'
                  | 'star'
                  | 'stickyNote'
                  | 'window';
                image?: (number | null) | Media;
                url?: string | null;
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            ctaLabel?: string | null;
            ctaLink?: string | null;
            footer?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'servicesAndMaterialsSection';
          }
        | {
            title: string;
            subtitle?: string | null;
            cards: {
              icon:
                | 'bell'
                | 'certified'
                | 'checkCircle'
                | 'deck'
                | 'documentCheck'
                | 'glasses'
                | 'gutter'
                | 'locationHeart'
                | 'meditation'
                | 'messages'
                | 'money'
                | 'paintBrush'
                | 'paymentCard'
                | 'roof'
                | 'roofCleaning'
                | 'roofInsulation'
                | 'roofRepair'
                | 'roofReplacement'
                | 'shieldCheck'
                | 'shield'
                | 'siding'
                | 'smile'
                | 'star'
                | 'stickyNote'
                | 'window';
              title: string;
              subtitle?: string | null;
              /**
               * Shows the card highlighted in gold, spanning two columns.
               */
              featured?: boolean | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'whyUsBoxes';
          }
        | {
            title: string;
            text?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            image: number | Media;
            ctaTitle?: string | null;
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'cardWithImageBackground';
          }
        | {
            title: string;
            subtitle?: string | null;
            reviews: {
              review: string;
              name: string;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'reviews';
          }
        | {
            variant: 'text' | 'bullets';
            title: string;
            /**
             * Google Maps embed URL (the src of the iframe from Share > Embed a map).
             */
            mapUrl?: string | null;
            text?: string | null;
            areas?:
              | {
                  name: string;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            linkLabel?: string | null;
            linkUrl?: string | null;
            bullets?:
              | {
                  text: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            footer?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'mapSection';
          }
        | {
            heading: string;
            subheading?: string | null;
            image: number | Media;
            items: {
              title: string;
              text: string;
              id?: string | null;
            }[];
            ctaLabel?: string | null;
            ctaLink?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checklistWithImage';
          }
        | {
            heading: string;
            subheading?: string | null;
            cards: {
              icon:
                | 'bell'
                | 'certified'
                | 'checkCircle'
                | 'deck'
                | 'documentCheck'
                | 'glasses'
                | 'gutter'
                | 'locationHeart'
                | 'meditation'
                | 'messages'
                | 'money'
                | 'paintBrush'
                | 'paymentCard'
                | 'roof'
                | 'roofCleaning'
                | 'roofInsulation'
                | 'roofRepair'
                | 'roofReplacement'
                | 'shieldCheck'
                | 'shield'
                | 'siding'
                | 'smile'
                | 'star'
                | 'stickyNote'
                | 'window';
              title: string;
              description?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'simpleCardSection';
          }
        | {
            variant: 'dark' | 'light';
            heading: string;
            text?: string | null;
            image: number | Media;
            /**
             * Steps are numbered automatically in the order they appear.
             */
            steps: {
              title: string;
              description?: string | null;
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'stepsSection';
          }
        | {
            heading: string;
            image: number | Media;
            questions: {
              question: string;
              answer: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'faqSection';
          }
        | {
            text?: string | null;
            cards: {
              title: string;
              text: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'locationCards';
          }
        | {
            heading: string;
            subheading?: string | null;
            counties: {
              name: string;
              locations: {
                location: string;
                locationUrl?: string | null;
                id?: string | null;
              }[];
              id?: string | null;
            }[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceAreasList';
          }
        | {
            id?: string | null;
            blockName?: string | null;
            blockType: 'blogPostsList';
          }
        | {
            heading: string;
            description?: string | null;
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactSection';
          }
      )[]
    | null;
  /**
   * What Google and social networks show. If a field is left empty, the page title or the default from Site Settings is used.
   */
  seo?: {
    /**
     * Title shown on Google. Ideal: up to 60 characters, with the main keyword first.
     */
    title?: string | null;
    /**
     * Summary shown under the title on Google. Ideal: between 120 and 160 characters.
     */
    description?: string | null;
    /**
     * If empty, the Meta title is used.
     */
    ogTitle?: string | null;
    /**
     * If empty, the Meta description is used.
     */
    ogDescription?: string | null;
    /**
     * Image shown when the link is shared. Recommended: 1200×630 px. If empty, the default image is used.
     */
    ogImage?: (number | null) | Media;
    ogType?: ('website' | 'article') | null;
    /**
     * Google will not show this page in search results. It is also left out of the sitemap.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
    /**
     * Only if this page duplicates another one. Leave empty to use this page's own URL.
     */
    canonicalUrl?: string | null;
    /**
     * schema.org scripts for this page (LocalBusiness, FAQPage, Service, etc.). Paste the JSON without the <script> tags.
     */
    jsonLd?:
      | {
          /**
           * Internal name to identify it (e.g. "LocalBusiness Bellevue").
           */
          label: string;
          /**
           * Valid JSON. If the JSON is malformed it cannot be saved.
           */
          schema:
            | {
                [k: string]: unknown;
              }
            | unknown[]
            | string
            | number
            | boolean
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt: string;
  excerpt?: string | null;
  featuredImage?: (number | null) | Media;
  cta?: {
    heading?: string | null;
    description?: string | null;
    ctaLabel?: string | null;
    ctaLink?: string | null;
  };
  postFaq?: {
    title?: string | null;
    image?: (number | null) | Media;
    questions?:
      | {
          question: string;
          answer: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[]
      | null;
  };
  category?: ('Roofing' | 'Decks') | null;
  /**
   * What Google and social networks show. If a field is left empty, the page title or the default from Site Settings is used.
   */
  seo?: {
    /**
     * Title shown on Google. Ideal: up to 60 characters, with the main keyword first.
     */
    title?: string | null;
    /**
     * Summary shown under the title on Google. Ideal: between 120 and 160 characters.
     */
    description?: string | null;
    /**
     * If empty, the Meta title is used.
     */
    ogTitle?: string | null;
    /**
     * If empty, the Meta description is used.
     */
    ogDescription?: string | null;
    /**
     * Image shown when the link is shared. Recommended: 1200×630 px. If empty, the default image is used.
     */
    ogImage?: (number | null) | Media;
    ogType?: ('website' | 'article') | null;
    /**
     * Google will not show this page in search results. It is also left out of the sitemap.
     */
    noIndex?: boolean | null;
    noFollow?: boolean | null;
    /**
     * Only if this page duplicates another one. Leave empty to use this page's own URL.
     */
    canonicalUrl?: string | null;
    /**
     * schema.org scripts for this page (LocalBusiness, FAQPage, Service, etc.). Paste the JSON without the <script> tags.
     */
    jsonLd?:
      | {
          /**
           * Internal name to identify it (e.g. "LocalBusiness Bellevue").
           */
          label: string;
          /**
           * Valid JSON. If the JSON is malformed it cannot be saved.
           */
          schema:
            | {
                [k: string]: unknown;
              }
            | unknown[]
            | string
            | number
            | boolean
            | null;
          id?: string | null;
        }[]
      | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 301/302 redirects. They are created automatically when the slug of a page or post changes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: number;
  /**
   * Old path, e.g. /roofing-seattle
   */
  from: string;
  /**
   * New path (/roofing/seattle) or full URL (https://...)
   */
  to: string;
  type: '301' | '302';
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'redirects';
        value: number | Redirect;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  components?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              description?: T;
              image?: T;
              ctaLabel?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        servicesAndMaterialsSection?:
          | T
          | {
              heading?: T;
              subheading?: T;
              groups?:
                | T
                | {
                    label?: T;
                    services?:
                      | T
                      | {
                          title?: T;
                          description?: T;
                          icon?: T;
                          image?: T;
                          url?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              ctaLabel?: T;
              ctaLink?: T;
              footer?: T;
              id?: T;
              blockName?: T;
            };
        whyUsBoxes?:
          | T
          | {
              title?: T;
              subtitle?: T;
              cards?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    subtitle?: T;
                    featured?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        cardWithImageBackground?:
          | T
          | {
              title?: T;
              text?: T;
              image?: T;
              ctaTitle?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        reviews?:
          | T
          | {
              title?: T;
              subtitle?: T;
              reviews?:
                | T
                | {
                    review?: T;
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        mapSection?:
          | T
          | {
              variant?: T;
              title?: T;
              mapUrl?: T;
              text?: T;
              areas?:
                | T
                | {
                    name?: T;
                    link?: T;
                    id?: T;
                  };
              linkLabel?: T;
              linkUrl?: T;
              bullets?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              footer?: T;
              id?: T;
              blockName?: T;
            };
        checklistWithImage?:
          | T
          | {
              heading?: T;
              subheading?: T;
              image?: T;
              items?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              ctaLabel?: T;
              ctaLink?: T;
              id?: T;
              blockName?: T;
            };
        simpleCardSection?:
          | T
          | {
              heading?: T;
              subheading?: T;
              cards?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stepsSection?:
          | T
          | {
              variant?: T;
              heading?: T;
              text?: T;
              image?: T;
              steps?:
                | T
                | {
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faqSection?:
          | T
          | {
              heading?: T;
              image?: T;
              questions?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        locationCards?:
          | T
          | {
              text?: T;
              cards?:
                | T
                | {
                    title?: T;
                    text?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        serviceAreasList?:
          | T
          | {
              heading?: T;
              subheading?: T;
              counties?:
                | T
                | {
                    name?: T;
                    locations?:
                      | T
                      | {
                          location?: T;
                          locationUrl?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        blogPostsList?:
          | T
          | {
              id?: T;
              blockName?: T;
            };
        contactSection?:
          | T
          | {
              heading?: T;
              description?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
      };
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        ogType?: T;
        noIndex?: T;
        noFollow?: T;
        canonicalUrl?: T;
        jsonLd?:
          | T
          | {
              label?: T;
              schema?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  publishedAt?: T;
  excerpt?: T;
  featuredImage?: T;
  cta?:
    | T
    | {
        heading?: T;
        description?: T;
        ctaLabel?: T;
        ctaLink?: T;
      };
  postFaq?:
    | T
    | {
        title?: T;
        image?: T;
        questions?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  category?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogTitle?: T;
        ogDescription?: T;
        ogImage?: T;
        ogType?: T;
        noIndex?: T;
        noFollow?: T;
        canonicalUrl?: T;
        jsonLd?:
          | T
          | {
              label?: T;
              schema?: T;
              id?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?: T;
  type?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  navLinks?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  links?:
    | {
        label: string;
        href: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  phone?: string | null;
  email?: string | null;
  license?: string | null;
  offices?:
    | {
        address: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Values used when a page leaves its own SEO field empty.
   */
  seo?: {
    /**
     * Production domain without a trailing slash, e.g. https://www.orcaroofing.com
     */
    siteUrl?: string | null;
    /**
     * e.g. Orca Roofing & Exteriors
     */
    siteName?: string | null;
    /**
     * Added at the end of every title. e.g. " | Orca Roofing"
     */
    titleSuffix?: string | null;
    defaultDescription?: string | null;
    defaultOgImage?: (number | null) | Media;
    /**
     * e.g. @orcaroofing
     */
    twitterHandle?: string | null;
  };
  /**
   * Leave empty whatever you don't use: only tools with an ID are loaded.
   */
  tracking?: {
    /**
     * e.g. GTM-XXXXXXX
     */
    gtmId?: string | null;
    /**
     * e.g. G-XXXXXXXXXX
     */
    gaId?: string | null;
    /**
     * Numbers only
     */
    metaPixelId?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  links?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  phone?: T;
  email?: T;
  license?: T;
  offices?:
    | T
    | {
        address?: T;
        id?: T;
      };
  seo?:
    | T
    | {
        siteUrl?: T;
        siteName?: T;
        titleSuffix?: T;
        defaultDescription?: T;
        defaultOgImage?: T;
        twitterHandle?: T;
      };
  tracking?:
    | T
    | {
        gtmId?: T;
        gaId?: T;
        metaPixelId?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}